# Generated by Django 5.2.1 on 2025-09-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinechatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='exhibit',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='image',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='start_date',
        ),
    ]
