# Generated by Django 6.0 on 2026-01-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinechatbot', '0002_staff_rename_end_date_exhibit_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuseumTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('open_time', models.CharField(blank=True, max_length=20, null=True)),
                ('close_time', models.CharField(blank=True, max_length=20, null=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
